; ============================================================================
; - dns.conf - DNS 过滤规则
; ----------------------------------------------------------------------------
; 用于 dns 插件，hook java.net.InetAddress 域名解析。
;
; 当域名匹配规则时，DNS 查询会返回 UnknownHostException。
;
; 格式：
;   [DNS]
;   EQUAL,domain.com
;   PREFIX,subdomain.example.com
; ============================================================================

[DNS]
EQUAL,jetbrains.com
EQUAL,plugin.obroom.com