; ============================================================================
; - native.conf - Native 方法包装规则
; ----------------------------------------------------------------------------
; 用于 native 插件，hook java.lang.ClassLoader 方法。
;
; 格式：
;   [Class]
;   EQUAL,com.example.MyClass
; ============================================================================

[Class]
; wrap specified classes